language: haxe

haxe:
  - 4.0.2

install:
  - haxelib git hscript https://github.com/HaxeFoundation/hscript.git
  - haxelib git hxbit https://github.com/HeapsIO/hxbit.git
  - haxelib git heaps https://github.com/HeapsIO/heaps.git
  - haxelib git castle https://github.com/ncannasse/castle.git
  - haxelib install format
  - haxelib install hldx
  - haxelib install hlopenal

script:
  - haxe hl.hxml
  - haxe js.hxml
  - haxe swf.hxml

notifications:
  slack: anagrammages:EtIhHhWsEUggGCYKulnafX3V

before_deploy:
  - zip -r cubeo.zip ./ --exclude=*LICENSE* --exclude=*.git* --exclude=*.vscode* --exclude=*src* --exclude=*.gitattributes* --exclude=*.gitignore* --exclude=*.yml* --exclude=*.hxml* --exclude=*.md* --exclude=*.bat*

deploy:
  provider: pages
  edge:
    branch: master
  token: ${GITHUB_TOKEN}
  name: latest development build
  cleanup: false
  on:
    tags: false
    branch: master